name: Release a new container image version

on:
  push:
    branches: ['main']
    tags: [ 'v*' ]
env:
  REGISTRY_IMAGE: ghcr.io/${{ github.repository }}

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
    secrets: inherit
  build:
    needs: [lint]
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: linux
          arch: amd64
          runner: ubuntu-24.04
          gorelease_v: "v1"
        - os: linux
          arch: arm64
          runner: ubuntu-24.04-arm
          gorelease_v: "v8.0"
    runs-on: ${{ matrix.runner }}
    outputs:
      linux-amd64: ${{ steps.digest.outputs.linux-amd64 }}
      linux-arm64: ${{ steps.digest.outputs.linux-arm64 }}
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v6
    - name: Set up buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to ghcr
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        args: build --single-target ${{ github.ref == 'refs/heads/main' && '--snapshot' || '' }}
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: dist/builds_${{ matrix.os }}_${{ matrix.arch }}_${{ matrix.gorelease_v }}
        file: Dockerfile
        platforms: ${{ matrix.os }}/${{ matrix.arch }}
        tags: ${{ env.REGISTRY_IMAGE }}
        labels: |
          org.opencontainers.image.description="Kubernetes generic external-dns webhook provider for libdns baked providers"
        outputs: type=image,push-by-digest=true,name-canonical=true,push=true
    - name: Export digest
      id: digest
      run: |
        printf "%s=%s" "${{ matrix.os }}-${{ matrix.arch }}" "${{ steps.build.outputs.digest }}" >> "$GITHUB_OUTPUT"

  merge:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: read
      packages: write
    steps:
    - name: Set up buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to ghcr
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY_IMAGE }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
    - name: Create manifest list and push
      run: |
        docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
          ${{ env.REGISTRY_IMAGE }}@${{ needs.build.outputs.linux-amd64 }} \
          ${{ env.REGISTRY_IMAGE }}@${{ needs.build.outputs.linux-arm64 }}
